def menu():
    print("*" * 50)
    print("\tEMP INFORMATION SYSTEM")
    print("*" * 50)
    print("\t\t1. New Employee")
    print("\t\t2. Delete Employee")
    print("\t\t3. Update Employee")
    print("\t\t4. View Single Employee")
    print("\t\t5. View All Employee")
    print("\t\t6. Search for Employee")
    print("\t\t7. Exit")
    print("*" * 50)